# See https://prek.j178.dev/ for more information
# Run `prek install` to install git hooks
# Run `prek run --all-files` to run all hooks on all files

repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: https://github.com/golangci/golangci-lint
    rev: e2e40021c9007020676c93680a36e3ab06c6cd33 # v2.8.0
    hooks:
      - id: golangci-lint-full

  - repo: https://github.com/gitleaks/gitleaks
    rev: 2ca41cc1372d1e939a6a879f18cdc19fc1cac1ce # v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/biomejs/pre-commit
    rev: 07ca3c2d657181455c0a68d6ddc8c931bff6d016 # v0.6.1
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.3.10"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 7339935a3036f096ee0d7f1f047a9ec41707d4c1 # v0.20.0
    hooks:
      - id: markdownlint-cli2
